// lib/firebase_options.dart
// Generated by FlutterFire CLI - vixo-bmi project
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError('Linux is not supported yet.');
      default:
        throw UnsupportedError('Unknown platform.');
    }
  }

  // Web config (from your Firebase project)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpCa0MaN0lnOjlpJUkLCa-nEqZKxmZFVE',
    authDomain: 'vixo-bmi.firebaseapp.com',
    databaseURL: 'https://vixo-bmi-default-rtdb.firebaseio.com',
    projectId: 'vixo-bmi',
    storageBucket: 'vixo-bmi.firebasestorage.app',
    messagingSenderId: '594964272405',
    appId: '1:594964272405:web:a58a615759f847b54f051c',
    // ignore: invalid_constant_pattern
    measurementId: 'G-HNPEK2SV81',
  );

  // Android - same web config works for Flutter Web builds
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpCa0MaN0lnOjlpJUkLCa-nEqZKxmZFVE',
    authDomain: 'vixo-bmi.firebaseapp.com',
    databaseURL: 'https://vixo-bmi-default-rtdb.firebaseio.com',
    projectId: 'vixo-bmi',
    storageBucket: 'vixo-bmi.firebasestorage.app',
    messagingSenderId: '594964272405',
    appId: '1:594964272405:android:6e836611a07d9d824f051c',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpCa0MaN0lnOjlpJUkLCa-nEqZKxmZFVE',
    authDomain: 'vixo-bmi.firebaseapp.com',
    projectId: 'vixo-bmi',
    storageBucket: 'vixo-bmi.firebasestorage.app',
    messagingSenderId: '594964272405',
    appId: '1:594964272405:ios:b176e06ee09ee5264f051c',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpCa0MaN0lnOjlpJUkLCa-nEqZKxmZFVE',
    authDomain: 'vixo-bmi.firebaseapp.com',
    projectId: 'vixo-bmi',
    storageBucket: 'vixo-bmi.firebasestorage.app',
    messagingSenderId: '594964272405',
    appId: '1:594964272405:ios:b176e06ee09ee5264f051c',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpCa0MaN0lnOjlpJUkLCa-nEqZKxmZFVE',
    authDomain: 'vixo-bmi.firebaseapp.com',
    projectId: 'vixo-bmi',
    storageBucket: 'vixo-bmi.firebasestorage.app',
    messagingSenderId: '594964272405',
    appId: '1:594964272405:web:cbb709fe27d59f5d4f051c',
  );
}
