version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - bidi
  - bmis
  - buildlog
  - calori
  - deadlifts
  - Devine
  - docstates
  - DUNICODE
  - endfunction
  - fixnum
  - ghrelin
  - glassmorphism
  - HIIT
  - hydrat
  - iconsax
  - Jeor
  - Mifflin
  - mmol
  - MULTICONFIG
  - NDZE
  - pbxproj
  - petitparser
  - playfair
  - pubspec
  - swiftpm
  - Symbolication
  - TDEE
  - userosscache
  - vitacheck
  - xcodeproj
ignoreWords: []
import: []
